[general]
world_name = "testserver"
password = "123456"
server_port = "14159"
player_slots = "10"
server_ip = "0.0.0.0"
server_owner = "username"
necesse_dir = "/home/steam/necesse_saves"

[windows]
win_dir = "..."

[linux]
linux_dir = "..."
